### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by sagarlakhia** [Zomato/AndroidPhotoFilters#8]
I'm not sure what's the issue here. It just throws IllegalStateException at the last line (Where I'm saving the output to Bitmap output). I followed all the proper steps. Can't figure out the problem.

`Bitmap output =filter.processFilter(oldBitmap);
`

**Comment by varunest** [comment]
Hi, can you comment the stack-trace of the issue as well. Will look into it.

**Comment by alexnuts** [comment]
Hello. I have the same error.

**stacktrace**:
`
java.lang.IllegalStateException
                                    at android.graphics.Bitmap.setPixels(Bitmap.java:1466)
                                    at com.zomato.photofilters.imageprocessors.ImageProcessor.doBrightness(ImageProcessor.java:45)
                                    at com.zomato.photofilters.imageprocessors.subfilters.BrightnessSubfilter.process(BrightnessSubfilter.java:28)
                                    at com.zomato.photofilters.imageprocessors.Filter.processFilter(Filter.java:88)
                                    at com.alexnuts.myimagefilteringexample.androidphotofilters.AndroidPhotoFiltersActivity.applyFilter(AndroidPhotoFiltersActivity.java:48)
                                    at com.alexnuts.myimagefilteringexample.androidphotofilters.AndroidPhotoFiltersActivity.changeFilter(AndroidPhotoFiltersActivity.java:43)
                                    at com.alexnuts.myimagefilteringexample.androidphotofilters.AndroidPhotoFiltersActivity.lambda$onCreate$8(AndroidPhotoFiltersActivity.java:71)
                                    at com.alexnuts.myimagefilteringexample.androidphotofilters.AndroidPhotoFiltersActivity$$Lambda$1.onClick(Unknown Source)
                                    at android.view.View.performClick(View.java:4811)
                                    at android.view.View$PerformClick.run(View.java:20136)
                                    at android.os.Handler.handleCallback(Handler.java:815)
                                    at android.os.Handler.dispatchMessage(Handler.java:104)
                                    at android.os.Looper.loop(Looper.java:194)
                                    at android.app.ActivityThread.main(ActivityThread.java:5546)
                                    at java.lang.reflect.Method.invoke(Native Method)
                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
`

**There is my code**
`
package com.alexnuts.myimagefilteringexample.androidphotofilters;

import android.graphics.*;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.widget.*;

import com.alexnuts.myimagefilteringexample.R;
import com.zomato.photofilters.SampleFilters;
import com.zomato.photofilters.imageprocessors.Filter;

/**
 * Created by alex on 21.09.16.
 */

public class AndroidPhotoFiltersActivity extends AppCompatActivity {
    private static final String TAG = AndroidPhotoFiltersActivity.class.getSimpleName();

    static {
        System.loadLibrary("NativeImageProcessor");
    }

    private ImageView uiPic;

    private Filter filterDefault;
    private Filter filterTarget;
    private Filter currentFilter;

    private Bitmap bitmap;

    protected void setCurrentFilter(Filter currentFilter) {
        this.currentFilter = currentFilter;
    }

    private void changeFilter() {
        if (this.currentFilter == filterDefault) {
            setCurrentFilter(filterTarget);
        } else {
            setCurrentFilter(filterDefault);
        }
        applyFilter();
    }

    private void applyFilter() {
        try {
            Bitmap filteredBitmap = currentFilter.processFilter(this.bitmap);
            uiPic.setImageBitmap(filteredBitmap);
            if (filteredBitmap != bitmap)
                Toast.makeText(this, "filter applied", Toast.LENGTH_SHORT).show();
        } catch (Throwable throwable) {
            Log.e(TAG, "", throwable);
        }
    }

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_androidphotofilter);

        uiPic = (ImageView) findViewById(R.id.pic);

        filterDefault = SampleFilters.getLimeStutterFilter();
        filterTarget = SampleFilters.getBlueMessFilter();

        BitmapFactory.Options opts = new BitmapFactory.Options();
        opts.inSampleSize = 10;
        bitmap = BitmapFactory.decodeResource(getResources(), R.drawable.wallpaper, opts);

        findViewById(R.id.apply).setOnClickListener(v -> changeFilter());

        uiPic.setImageBitmap(bitmap);
    }

}
`

**layout**:

`
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <ImageView
        android:id="@+id/pic"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        android:orientation="horizontal">

        <Button
            android:id="@+id/apply"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:text="Apply Filter" />

        <Button
            android:id="@+id/save"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:text="Save" />

    </LinearLayout>

</FrameLayout>
`
**image:**

[https://wallpapers.wallhaven.cc/wallpapers/full/wallhaven-305515.jpg](url)

**Comment by alexnuts** [comment]
I have found solution:
You have to import you image as mutable bitmap:

`        
BitmapFactory.Options opts = new BitmapFactory.Options();
opts.inMutable = true;
`

**Comment by varunest** [comment]
Yes that is correct. By default **decodeResouce** returns inMutable copy of bitmap which can't be modified.

**Comment by asywalulfikri** [comment]
how add button save image and Intent image after filter into new class,  to show in imageview

**Comment by sagarlakhia** [comment]
Sorry for late response: The thing is I'm saving the bitmap to external storage and when I'm trying to apply filter it throws following error:
```
 java.lang.IllegalStateException
                                                                             at android.graphics.Bitmap.setPixels(Bitmap.java:1605)
                                                                             at com.zomato.photofilters.imageprocessors.ImageProcessor.doSaturation(ImageProcessor.java:82)
                                                                             at com.zomato.photofilters.imageprocessors.subfilters.SaturationSubfilter.process(SaturationSubfilter.java:23)
                                                                             at com.zomato.photofilters.imageprocessors.Filter.processFilter(Filter.java:88)
                                                                             at com.blackfruit.camfilters.ImageFilterActivity.setSaturation(ImageFilterActivity.java:217)
                                                                             at com.blackfruit.camfilters.ImageFilterActivity.updateFilter(ImageFilterActivity.java:180)
                                                                             at com.blackfruit.camfilters.ImageFilterActivity$RecyclerViewAdapter$1.onClick(ImageFilterActivity.java:449)
                                                                             at android.view.View.performClick(View.java:4753)
                                                                             at android.view.View$PerformClick.run(View.java:19562)
                                                                             at android.os.Handler.handleCallback(Handler.java:733)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:146)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5635)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                                             at dalvik.system.NativeStart.main(Native Method)
```
Can anyone help me out with this?

**Comment by sagarlakhia** [comment]
Sorry figured it out. It was inMutable problem.

**Comment by mahdihp** [comment]
java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalStateException
        at android.graphics.Bitmap.setPixels(Bitmap.java:2119)
        at com.zomato.photofilters.imageprocessors.ImageProcessor.doColorOverlay(ImageProcessor.java:70)
        at com.zomato.photofilters.imageprocessors.subfilters.ColorOverlaySubFilter.process(ColorOverlaySubFilter.java:40)
        at com.zomato.photofilters.imageprocessors.Filter.processFilter(Filter.java:115)
        at com.mahdi.ketabcell.activity.imageedit.FilterActivity$BitmapFilterAsync.doInBackground(FilterActivity.java:520)
        at com.mahdi.ketabcell.activity.imageedit.FilterActivity$BitmapFilterAsync.doInBackground(FilterActivity.java:498)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by muhammad-sameer-amjad** [comment]
I just made my bitmap to mutable bitmap
inputImage = inputImage.copy(Bitmap.Config.ARGB_8888,true);
